### ISSUE TITLE
hk_3dva@DESKTOP-8VP5C77:~/trape$ pip install -r requirements.txt Invalid requirement: '<<<<<<< HEAD' Traceback (most recent call last):   File "/home/hk_3dva/.local/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line     req = Requirement(req)   File "/home/hk_3dva/.local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__     requirement_string[e.loc:e.loc + 8], e.msg InvalidRequirement: Parse error at "u'<<<<<<< '": Expected W:(abcd...)     what should I do????

### ISSUE THREAD

**Issue by hk3dva** [jofpin/trape#106]

**Comment by hk3dva** [comment]
what should I do
