### ISSUE TITLE
Trape waiting for users to fall and Control panel No update

### ISSUE THREAD

**Issue by freeman68** [jofpin/trape#133]
HI,

Does anyone know how to fix the problem with trape where you send the link and it gets opened, but now sessions pop up on the control panel and waiting for users to fall shoes nothing?

Please help/

@DJCHICKEN4  @jofpin

**Comment by DJCHICKEN4** [comment]
I have attempted to recreate this problem before without any luck. And it seems many people are experiencing this issue. Could you give me some more information such as what OS you are running, what command you are running and if you could copy the console error that would be great.

**Comment by freeman68** [comment]
@DJCHICKEN4 
Thank you for your reply, I am using kali linux, did all the updates and all that,

I am getting no error at all, everything is going right, nothing happens at all, 
my commands Ive tried,
python2 trape.py -u URL -p 8080
python trape.py -u URL -p 8080
python2 trape.py --url http://example.com --port 8080

I have tried different ports,

I get no error, nothing isnt happening when I open the lure link, i have tried it on many different computers, phones and all that. And they are windows 10 pc and android phones.

And no console error.

**Comment by freeman68** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f3279637058456a2e706e67](https://user-images.githubusercontent.com/47744112/53303734-ad854700-3876-11e9-8671-f19e8e5962f9.png)

**Comment by freeman68** [comment]
I get to that screen and then I do the rest and nothing happens, even left it for a few hours to see if something happens later, but nothing happens.

**Comment by DJCHICKEN4** [comment]
@freeman68 I'll try and recreate the error and get back to you as soon as I either have a solution or if it needs a patch

**Comment by freeman68** [comment]
Thank you very much, 
Really appreciate it :)

**Comment by DJCHICKEN4** [comment]
One last question are you using the local link or the ngrok link?

**Comment by freeman68** [comment]
@DJCHICKEN4 
I think it has something to do with the API keys, 
Because when you launch trape v2 for the first time, you first have to register on that ngrok website and get an API key there and then you have to get the google maps API key, and I think the problem is with the google maps api key. Just my theory.

**Comment by freeman68** [comment]
> 
> 
> One last question are you using the local link or the ngrok link?

I am not sure what you are talking about now? Could you please elaborate?

**Comment by DJCHICKEN4** [comment]
@freeman68 Yes when you run the command do you use the public link or local link?

**Comment by freeman68** [comment]
> 
> 
> One last question are you using the local link or the ngrok link?

@DJCHICKEN4  if you talking about the public information and local information links like on the screenshot, I tried both.

**Comment by DJCHICKEN4** [comment]
@freeman68 Have you recently (within the last week) tried removing and reinstalling it.

**Comment by DJCHICKEN4** [comment]
@freeman68 Could you go to the lure on your windows machine then once it has loaded press ctrl+shift+i, then click onto console and take a screenshot of the errors.

**Comment by freeman68** [comment]
t_start cevin.harding:3:1207
Request to access cookie or storage on “https://www.facebook.com/cevin.harding/data:text/css;%20charset=utf-8;base64,I2Jvb3Rsb2FkZXJfUF9tcjV7aGVpZ2h0OjQycHg7fS5ib290bG9hZGVyX1BfbXI1e2Rpc3BsYXk6YmxvY2shaW1wb3J0YW50O30=” was blocked because it came from a tracker and content blocking is enabled. cevin.harding
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] cevin.harding
t_domcontent cevin.harding:3:1207
t_tti cevin.harding:3:1207
Voice support NOT ready
262fcfb48f48:34:29757
RV: Voice support ready 262fcfb48f48:34:29676
t_prehooks cevin.harding:3:1207
t_hooks cevin.harding:3:1207
ReferenceError: UAParser is not defined[Learn More] 526d082ee967:8:13
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. referer_frame.php
t_layout cevin.harding:3:1207
perf_trace {"name": "e2e", "parent": "PageEvents.BIGPIPE_ONLOAD"} WVSwAaIjKiC.js:121:2787
t_paint cevin.harding:3:1207
ErrorUtils caught an error: "<![EX[["Async request failed with error %s: %s when requesting %s TAAL[2;2]",...". Subsequent errors won't be logged; see https://fburl.com/debugjs. WVSwAaIjKiC.js:55:6186
Request to access cookie or storage on “https://cx.atdmt.com/?f=AYxiZV664HKUN0coYLdV1amMIUJD4NPosO7ADUAOJZseIRQddAm8qV6yhhH5r9Cx649YIKKUW53aftGeUDKFTNoc&c=1532429724&v=1&l=2” was blocked because it came from a tracker and content blocking is enabled. cevin.harding
Request to access cookie or storage on “https://cx.atdmt.com/?f=AYxiZV664HKUN0coYLdV1amMIUJD4NPosO7ADUAOJZseIRQddAm8qV6yhhH5r9Cx649YIKKUW53aftGeUDKFTNoc&c=1532429724&l=2” was blocked because it came from a tracker and content blocking is enabled. cevin.harding
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: http://1af95c35.ngrok.io/static/js/262fcfb48f48
Source Map URL: socket.io.js.map[Learn More]

**Comment by DJCHICKEN4** [comment]
I managed to recreate it and I think I may have a solution try opening the lure link in an incognito tab.

**Comment by freeman68** [comment]
I tried, but still the same, but I will try again in a few hours.

When I cntrl+c my trape, i get this error, can this mean anything?

^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
  File "/usr/lib/python2.7/subprocess.py", line 217, in check_output
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 475, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
  File "/usr/local/lib/python2.7/dist-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt

**Comment by DJCHICKEN4** [comment]
@freeman68 I'm sorry I wasn't able to be of much help. I'll see if I can come up with something but I'm not sure I'll be able to as I can't recreate the issue properly. @jofpin Do you have any ideas as to what is happening or how to recreate the issue because if I can do that I'll likely be able to fix the problem.

**Comment by freeman68** [comment]
@DJCHICKEN4 

Thank you very much for the effort, lets see if @jofpin can maybe help :)

**Comment by lordcharlx** [comment]
[2019-03-01 23:27:23,797] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zeus/Desktop/trape/core/stats.py", line 94, in home_get_title
    html = opener.open(trape.url_to_clone).read()
  File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

![screenshot at 2019-03-01 23-29-57](https://user-images.githubusercontent.com/5570136/53670166-f6c00700-3c79-11e9-8dc3-22bcd583d91b.png)

**Comment by freeman68** [comment]
@lordcharlx 

> [2019-03-01 23:27:23,797] ERROR in app: Exception on /get_title [POST]
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
> return cors_after_request(app.make_response(f(*args, **kwargs)))
> File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/home/zeus/Desktop/trape/core/stats.py", line 94, in home_get_title
> html = opener.open(trape.url_to_clone).read()
> File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 406, in open
> response = meth(req, response)
> File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 519, in http_response
> 'http', request, response, code, msg, hdrs)
> File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 444, in error
> return self._call_chain(*args)
> File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 378, in _call_chain
> result = func(*args)
> File "/home/zeus/Desktop/trape/core/dependence/urllib2.py", line 527, in http_error_default
> raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> HTTPError: HTTP Error 403: Forbidden
> 
> ![screenshot at 2019-03-01 23-29-57](https://user-images.githubusercontent.com/5570136/53670166-f6c00700-3c79-11e9-8dc3-22bcd583d91b.png)

Try using another link, like a facebook profile or something.

**Comment by Ameya711** [comment]
Hi, 

Can anyone help me please? I'm very new (2 days in) to all of this so please be patient with me!

I'm trying to run trape but I'm stuck here - 
![image](https://user-images.githubusercontent.com/50630884/57710903-69425f80-768b-11e9-8867-fae941186adc.png)

**Comment by carlocrasti** [comment]
> I tried, but still the same, but I will try again in a few hours.
> 
> When I cntrl+c my trape, i get this error, can this mean anything?
> 
> ^CProcess Process-1:
> Traceback (most recent call last):
> File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
> self.run()
> File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
> self._target(*self._args, **self._kwargs)
> File "/root/Trape/core/ngrok.py", line 81, in start_ngrok
> result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
> File "/usr/lib/python2.7/subprocess.py", line 217, in check_output
> output, unused_err = process.communicate()
> File "/usr/lib/python2.7/subprocess.py", line 475, in communicate
> stdout = _eintr_retry_call(self.stdout.read)
> File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
> return func(*args)
> File "/usr/local/lib/python2.7/dist-packages/engineio/client.py", line 41, in signal_handler
> return original_signal_handler(sig, frame)
> KeyboardInterrupt

**Comment by carlocrasti** [comment]
Same error here. Any solution ?

**Comment by iloveyoumaya** [comment]
why is trape control pane wesite not opening
