### ISSUE TITLE
always getting this error   even before the attack begins

### ISSUE THREAD

**Issue by lordcharlx** [jofpin/trape#134]
![screenshot at 2019-02-28 10-14-39](https://user-images.githubusercontent.com/5570136/53555283-ea389300-3b41-11e9-95bc-a62a43d5ed05.png)

**Comment by lordcharlx** [comment]
[¡] Waiting for the users to fall...

[2019-02-28 10:31:02,924] ERROR in app: Exception on /gmail.com [GET]
Traceback (most recent call last):
  File "/home/ghost/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ghost/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Cors-3.0.7-py2.7.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ghost/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ghost/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ghost/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ghost/Desktop/trape/core/user.py", line 69, in homeVictim
    html = assignScripts(victim_inject_code(opener.open(trape.url_to_clone).read(), 'payload', trape.url_to_clone, trape.gmaps))
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 418, in _open
    '_open', req)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/home/ghost/Desktop/trape/core/dependence/urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 0] Error>

**Comment by AnonymousTamizhan** [comment]
i'm also getting the same error
