### ISSUE TITLE
We can't connect with ngrok

### ISSUE THREAD

**Issue by Parshuram2** [jofpin/trape#139]
Yes, I have unzip and a valid ngrok key

**Comment by HackersPlace** [comment]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '80', '-log', '27fa7c8.nlog']' returned non-zero exit status 1
	---=[ We can't connect with nGrok

**Comment by Andersonxqt** [comment]
Hi, same error here :
Process Process-1:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '80', '-log', '8b22fa5.nlog']' returned non-zero exit status 1
	---=[ We can't connect with nGrok

**Comment by ahmedali4533** [comment]
Process Process-1:                                                                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                                           
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap                                                                                                                                                              
    self.run()                                                                                                                                                                                                                               
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run                                                                                                                                                                     
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                
  File "/home/buttsahab/trape/core/ngrok.py", line 81, in start_ngrok                                                                                                                                                                        
    result = subprocess.check_output([str_ngrok, "http", port])                                                                                                                                                                              
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output                                                                                                                                                                         
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                                                                                         
  File "/usr/lib/python3.9/subprocess.py", line 528, in run                                                                                                                                                                                  
    raise CalledProcessError(retcode, process.args,                                                                                                                                                                                          
subprocess.CalledProcessError: Command '['./ngrok', 'http', '80']' returned non-zero exit status 1.
