### ISSUE TITLE
 ERROR in app: Exception on /register [POST]

### ISSUE THREAD

**Issue by cr4shcod3** [jofpin/trape#153]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/trape/core/user.py", line 98, in register
    db.sentences_victim('insert_victim', [victimConnect, vId, time.time()], 2)
  File "/home/user/trape/core/db.py", line 153, in sentences_victim
    return self.sql_insert(self.prop_sentences_victim(type, data))
  File "/home/user/trape/core/db.py", line 55, in sql_insert
    self.conn.commit()
OperationalError: disk I/O error

Any fix to this? Is the error related to Flask?

**Comment by prd-dahal** [comment]
.
