### ISSUE TITLE
Idk why is this happening, any solution?

### ISSUE THREAD

**Issue by origmz** [jofpin/trape#164]
C:\Users\Usuario\Desktop\trape>python trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "C:\Users\Usuario\Desktop\trape\core\utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

**Comment by origmz** [comment]
> @origmz Run this command `python2 -m pip install -r requirements.txt`

I already tried it, but it doesn't recognize it as a command
