### ISSUE TITLE
ERROR:  gooGl forbidden

### ISSUE THREAD

**Issue by Worem** [jofpin/trape#173]
Help D: i have this problem with trape
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cristianavalos/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '80', '-log', 'bf31da6.nlog']' returned non-zero exit status 1
	PUBLIC INFORMATION
 ERROR:  gooGl forbidden anyone know how to fix it?

**Comment by mathiasconradt** [comment]
Duplicate to https://github.com/jofpin/trape/issues/126
(Getting the same message by the way)

**Comment by hwac121** [comment]
Goo.gl service is no longer working, which is why we are getting this error. Perhaps swap it out with another service like bitly or the likes?
