### ISSUE TITLE
ngrok error

### ISSUE THREAD

**Issue by JoKerJAYS** [jofpin/trape#181]
When executing the command https://github.com/jofpin/trape/issues/141 the error "Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Репозитории/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port, '-log', hash + '.nlog'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '8080', '-log', 'cd50ed8.nlog']' returned non-zero exit status 1
[x] ERROR:  
	---=[ We can't connect with nGrok "

gets out, help I don’t know what to do

**Comment by SandorSzavost28** [comment]
PUBLIC INFORMATION
	-------------------
[x] ERROR:  No JSON object could be decoded
	---=[ We can't connect with nGrok

**Comment by axeldiazortega** [comment]
I have the same error, it is a possible solution please?

**Comment by alexhak1** [comment]
me too

**Comment by omharwalkar21** [comment]
When executing the command python3 trape.py -u https://en.wikipedia.org/wiki/Image --port 8080
Process Process-1:                                                                                                  
Traceback (most recent call last):                                                                                  
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap                                     
    self.run()                                                                                                      
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run                                            
    self._target(*self._args, **self._kwargs)                                                                       
  File "/home/om/trape/core/ngrok.py", line 81, in start_ngrok                                                      
    result = subprocess.check_output([str_ngrok, "http", port])                                                     
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output                                                
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                
  File "/usr/lib/python3.9/subprocess.py", line 528, in run                                                         
    raise CalledProcessError(retcode, process.args,                                                                 
subprocess.CalledProcessError: Command '['./ngrok', 'http', '8080']' returned non-zero exit status 1.               
[x] ERROR: 'URLError' object has no attribute 'message' 



gets out, help I don’t know what to do.

**Comment by Krytish** [comment]
> зает, помогите не знаю что делать.
++++

**Comment by MisterResponsible01** [comment]
Keep getting this 

Process Process-1:                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                    
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap                                                                                      
    self.run()                                                                                                                                                        
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run                                                                                             
    self._target(*self._args, **self._kwargs)                                                                                                                         
  File "/root/Desktop/trape/core/ngrok.py", line 81, in start_ngrok                                                                                                   
    result = subprocess.check_output([str_ngrok, "http", port])                                                                                                       
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output                                                                                                 
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                  
  File "/usr/lib/python3.10/subprocess.py", line 524, in run                                                                                                          
    raise CalledProcessError(retcode, process.args,                                                                                                                   
subprocess.CalledProcessError: Command '['./ngrok', 'http', '8080']' returned non-zero exit status 1.                                                                 
        @-=[ UPDATES: NEW VERSION IS AVAILABLE: v2.0 (install changes)      

[x] ERROR: 'URLError' object has no attribute 'message'  

I keep getting this any solutions??
