### ISSUE TITLE
Trape run error

### ISSUE THREAD

**Issue by anukiller** [jofpin/trape#203]
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/data/data/com.termux/files/home/trape/core/utils.py", line 23, in <module>
    import http.client
ImportError: No module named http.client

**Comment by harshitm98** [comment]
Kindly check [this comment](https://github.com/jofpin/trape/issues/199#issuecomment-576370067) on a similar issue. Should fix it.

**Comment by anukiller** [comment]
What is the location of http.client

**Comment by harshitm98** [comment]
You'll have to replace it in **utils.py** file. The path to utils.py file in your case is /data/data/com.termux/files/home/trape/core/utils.py

**Comment by anukiller** [comment]
Please tell me how to replace it

**Comment by harshitm98** [comment]
This issue has been fixed in the new build. Kindly update. 

To update:
`python trape.py --update`
