### ISSUE TITLE
                             [x] ERROR: local variable 'config_trape' referenced before assignment

### ISSUE THREAD

**Issue by ashwitha112** [jofpin/trape#218]
[x] ERROR: local variable 'config_trape' referenced before assignment

**Comment by BreathOfShadow** [comment]
I have same problem, and many people too.. How fix this ?

**Comment by sumitprajapat296** [comment]
how fix this problem??

**Comment by roltsolen** [comment]
Comment is by someone else, but it helped me. You can try it yourself 
"Hello my good friends here is the solution to the loop.
Steps:

Visit your trape folder.
2 Open the core folder and you'll find trape.py.
Open the trape.py folder and do what I'll illustrate.
Do this :
find:
v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '"\n\t"ipinfo_api_key" : "' + c_ipinfo + '"**,**\n}'
replace with:
v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '"**,**\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'
Find me later and buy some lunch haha.

"

**Comment by Zomka** [comment]
Traceback (most recent call last):
  File "trape.py", line 24, in <module>
    from core.trape import Trape                  #
  File "/root/trape/core/trape.py", line 282
    v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '"\n\t"ipinfo_api_key" : "' + c_ipinfo + '",\n}'v = '{\n\t"ngrok_token" : "' + c_nGrokToken + '",\n\t"gmaps_api_key" : "' + c_gMapsToken + '",\n\t"gshortener_api_key" : "' + c_gOoglToken + '",\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'
                                                                                                                                                                                                 ^
SyntaxError: invalid syntax

**Comment by roltsolen** [comment]
'",\n\t"gshortener_api_key" : "' + c_gOoglToken + '",\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'
^                                                                          ^

**Comment by roltsolen** [comment]
**Basically what you need to change is the final line from: (Commas)**
'"\n\t"ipinfo_api_key" : "' + c_ipinfo + '",\n}'
**TO:**
'",\n\t"ipinfo_api_key" : "' + c_ipinfo + '"\n}'
-^------------------------------------^
There is 2 commas you need to change

**Comment by Zomka** [comment]
Thanks, I already figured it out

**Comment by Orangeeye777** [comment]
[x] ERROR: local variable 'config_trape' referenced before assignment 

ISSUE RESOLVED :

Update the details properly while configuring the trape.config
i have use below site, create the account
1. ngrok - for ngrok_token
2. app.ipgeolocation.io - for gmaps_api_key
3. No need to update google url shorner
4. ipinfo.io - for ipinfo_api_key
Then hit ENTER. we are done...
