### ISSUE TITLE
ERROR TARCEBACK

### ISSUE THREAD

**Issue by tonovicio** [jofpin/trape#224]
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/marlon/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

**Comment by tonovicio** [comment]
sudo ./trape.py
[sudo] password for marlon: 
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/marlon/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

**Comment by TheMasterOfE** [comment]
@tonovicio Please read the README.md before making an issue thread. Thanks!

**Comment by THEpWn3R-o** [comment]
pip2 install requests
