### ISSUE TITLE
Error with trape: We cant connect to ngrok yet I have ngrok running

### ISSUE THREAD

**Issue by fkay9000** [jofpin/trape#227]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/francis/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '80']' returned non-zero exit status 1
[x] ERROR:  
	---=[ We can't connect with nGrok

**Comment by fkay9000** [comment]
I tried running ngrok on a separate terminal.

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/francis/trape/core/ngrok.py", line 81, in start_ngrok
    result = subprocess.check_output([str_ngrok, "http", port])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['./ngrok', 'http', '80']' returned non-zero exit status 1
[x] ERROR:

**Comment by mda1125** [comment]
Just got this working and noticed "We Can't connected to nGrok"

Running into the same problem.  But I have the right auth token.

**Comment by fkay9000** [comment]
> Just got this working and noticed "We Can't connected to nGrok"
> 
> Running into the same problem. But I have the right auth token.

Maybe it's an error with the program

**Comment by mda1125** [comment]
Well one tutorial shows it's a Tunnel Auth token you need.
https://www.securitynewspaper.com/2018/11/29/track-people-on-internet-trape-demo-tutorial/

When you logon to nGrok, you get an Auth token for the program but the Tunnel Auth being shown in the demos, is now an Enterprise feature, contact sales.

So maybe it works but not unless you go spend a bunch on a Tunnel Token specifically which doesn't seem to be an option anymore.

**Comment by nipungunathilaka1995** [comment]
did it work?

**Comment by Mayur8991** [comment]
Reset the ngrok authtoken from nrgok website and try again.
I had the same issue.
thanks

**Comment by Noideawhatdo** [comment]
I am in the same boat.. I can't get ngrok to work with any tool actually.  Is there a way to bypass that in Trape? An alternative we can use.. this tool looks like its amazing but it has been a tease! lol please help!

**Comment by Pan666tacc** [comment]
I don't know how to restore my ngrok authtoken because I change it. Somebody can help me pleaseeee
