### ISSUE TITLE
cant run trape 

### ISSUE THREAD

**Issue by jigsaw678** [jofpin/trape#240]
`root@kali:~/trape# ./trape.py
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
root@kali:~/trape# python trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
root@kali:~/trape# python2 trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
root@kali:~/trape# python3 trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
`

**Comment by ShellarFX** [comment]
`pip install httplib`

**Comment by jigsaw678** [comment]
@ShellarFX 
`pip install httplib
/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                          
ERROR: Could not find a version that satisfies the requirement httplib (from versions: none)                                                          
ERROR: No matching distribution found for httplib
`

**Comment by shubhampuri240** [comment]
same problem
can anyone please help  ........


Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/livingl/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
