### ISSUE TITLE
Unable to run trape.py

### ISSUE THREAD

**Issue by AltRuskie** [jofpin/trape#243]
error when command python2 trape.py is run

Traceback (most recent call last):
   File "trape.py", line 24, in <module>
       from core.trape import Trape
   File " /home/kali/Desktop/trape/core/trape.py", line 304 in <module>
       readline.set_completer(utils.niceShell)
AttributeError: 'module' object has no attribute 'niceShell'

Notes:
* Updated pip for python2 and installed all the requirements from requirements.txt

**Comment by animasola666** [comment]
try python,python2 - don't use

**Comment by Rozen10** [comment]
Change `httplib` by `http.client`

**Comment by Rozen10** [comment]
> > try python,python2 - don't use
> > $ cd trape
> > $ python trape.py
> 
> Still not working it says no module called httplib for python

Change httplib by http.client
