### ISSUE TITLE
NGROK NOT WORKING 

### ISSUE THREAD

**Issue by Forbesgriffin** [jofpin/trape#248]
Can anyone like fork this repo and fix the ngrok issue ,like include another tunnel like pagekite, localxpose and more _

**Comment by infoinline** [comment]
Hey, did you manage to sort this? I am having same issue.

**Comment by Forbesgriffin** [comment]
> Hey, did you manage to sort this? I am having same issue.

YES ,i did

**Comment by Forbesgriffin** [comment]
Try my forked repo [https://github.com/Forbesgriffin/trape](url)

**Comment by Forbesgriffin** [comment]
https://github.com/Forbesgriffin/trape

**Comment by ktjd123** [comment]
@Forbesgriffin the fork you gave link has conflit I guess??

```python
Traceback (most recent call last):
  File "trape.py", line 24, in <module>
    from core.trape import Trape                  #
  File "/Users/peter/Documents/hacking/trape/core/trape.py", line 207
    @@ -225,6 +228,7 @@ def header(self)
```

Thank you always appreciate your work.

**Comment by Forbesgriffin** [comment]
> @Forbesgriffin the fork you gave link has conflit I guess??
> 
> ```python
> Traceback (most recent call last):
>   File "trape.py", line 24, in <module>
>     from core.trape import Trape                  #
>   File "/Users/peter/Documents/hacking/trape/core/trape.py", line 207
>     @@ -225,6 +228,7 @@ def header(self)
> ```
> 
> Thank you always appreciate your work.

Try this [https://github.com/tdenisenko/trape](url)

**Comment by ktjd123** [comment]
> > @Forbesgriffin the fork you gave link has conflit I guess??
> > ```python
> > Traceback (most recent call last):
> >   File "trape.py", line 24, in <module>
> >     from core.trape import Trape                  #
> >   File "/Users/peter/Documents/hacking/trape/core/trape.py", line 207
> >     @@ -225,6 +228,7 @@ def header(self)
> > ```
> > 
> > 
> > Thank you always appreciate your work.
> 
> Try this [https://github.com/tdenisenko/trape](url)

Thank you for reply @Forbesgriffin .
![스크린샷 2020-07-08 오후 10 12 15](https://user-images.githubusercontent.com/15044488/86922791-19b0d400-c168-11ea-8a17-e0aab9dbecda.png)
the another fork you gave me gave another error.

maybe I should make it working if there is none maintained

**Comment by puthusseri** [comment]
Download the ngrok . Run it in another terminal as
ngrok http 8080
Before running the trape.py
It resolved the same error for me.
