### ISSUE TITLE
Tracback 

### ISSUE THREAD

**Issue by theadp** [jofpin/trape#259]
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/Desktop/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
root@kali:~/Desktop/trape# python2 trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/Desktop/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named request

what to do

**Comment by kaylasantos885** [comment]
python2 -m pip install -r requirements.txt
