### ISSUE TITLE
Can't launch trape python trace back issue 

### ISSUE THREAD

**Issue by jigsaw678** [jofpin/trape#263]
`13:04:33 root:~/trape #? $ python3 trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
13:04:38 root:~/trape #? $ python trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests
13:04:41 root:~/trape #? $ 

`

**Comment by OdincoGaming** [comment]
did you pip install requests?

**Comment by SaeedTufail** [comment]
When I try to install pip
bash: pip: command not found

**Comment by jigsaw678** [comment]
i tried pip

**Comment by aniket214** [comment]
how to solve this problem
![Screenshot from 2020-11-23 21-10-33](https://user-images.githubusercontent.com/66845633/100044081-bd0f3680-2e34-11eb-93a3-a1fb017362d7.png)

**Comment by abdullzz** [comment]
devs should consider moving to python3. since the problem will keep coming back as long as we use python2, it is no longer supported as the official says brother.
