### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by blackcatpro777** [jofpin/trape#266]
Traceback (most recent call last):
  File "trape.py", line 40, in <module>
    generateData = Database()
  File "/tools/trape/core/db.py", line 21, in __init__
    self.conn = sqlite3.connect("database.db", check_same_thread=False)
sqlite3.OperationalError: unable to open database file
Exception AttributeError: "'Database' object has no attribute 'conn'" in <bound method Database.__del__ of <core.db.Database object at 0x7fb1139aeb10>> ignored

**Comment by blackcatpro777** [comment]
To resolve the above mentioned error:
1. Create "database.db" using (sqlite3 database.db "") in the folder where trape is installed.
2. Provide write permissions to folder and database.db
