### ISSUE TITLE
Trape is not runing need your Kind Help 

### ISSUE THREAD

**Issue by Sallysheridan** [jofpin/trape#269]
whatsapp@kali2:~/trape$ python2 trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/whatsapp/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

Using python2 and according to most of complains ,, have instaled requirements.txt, have installed manually the flasks,,, >
Already Ngrok runing.....etc... But still cant make Trape to run.. Also have tryed on python3 with a different error that remarks non htlib module error

Please dear Jofpin, I am your Fan!! Help!

**Comment by noobyogi0010** [comment]
Hi @Sallysheridan !
Did you install the "requests" package?
Thanks.

**Comment by nymbuzcumulus** [comment]
yes, did absolutely :)

**Comment by noobyogi0010** [comment]
Okay @nymbuzcumulus 
I will try to reproduce this and try to see what is the problem you're facing.
Thanks.

**Comment by Sallysheridan** [comment]
thks noobyogi!  Any help to make it run properly is more than aclaimed and thanked!
