### ISSUE TITLE
Even about installing requests model still giving error

### ISSUE THREAD

**Issue by himanshu091109** [jofpin/trape#280]
/trape# python trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

**Comment by Edith-panda** [comment]
check for requests module if its fully installed or else some submodules are missing try installing it again and check for other modules as well and check for latest versions of modules

**Comment by Rozen10** [comment]
You can try to import request.[module_name] it's works for me
