### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by superman-enamy** [jofpin/trape#283]
Traceback (most recent call last):
File "./trape.py", line 23, in
from core.utils import utils #
File "/home/marlon/trape/core/utils.py", line 21, in
import requests,json
ImportError: No module named requests

**Comment by Edith-panda** [comment]
try installing requests python module first
for windows try command
pip install requests
and also check for json module likewise

**Comment by shubhampuri240** [comment]
> try installing requests python module first
> for windows try command
> pip install requests
> and also check for json module likewise
what should we do for linux
