### ISSUE TITLE
ModuleNotFoundError: No module named 'httplib'

### ISSUE THREAD

**Issue by techyboy188** [jofpin/trape#286]
root@kali:~/trape# python3 trape.py
Traceback (most recent call last):
  File "/root/trape/trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/root/trape/core/utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

please fix this issue..................thank you

**Comment by abdullzz** [comment]
you must be using python 3.8? me having same problem

**Comment by C4l1b3r** [comment]
Same issue
