### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Tajmirul** [jofpin/trape#295]
`pip install -r requirements.txt`
`Requirement already satisfied`
but when I run `python2 trape.py --url https://facebook.com --port 8080` it returns an error:

```
  Traceback (most recent call last):
    File "trape.py", line 23, in <module>
      from core.utils import utils                  #
    File "/home/nipon/Desktop/trape/core/utils.py", line 21, in <module>
      import requests, json
  ImportError: No module named requests
```

**Comment by puthusseri** [comment]
Maybe the packet manager pip is by default for the python3 in your system.
You can verify it by checking the version information of the pip using the following 
`pip -V`
The output will contain the python version also, in which all the packages will be associated.
If it is showing as python3, you need to install the pip for the python2.
