### ISSUE TITLE
[x] ERROR: __init__() got an unexpected keyword argument 'version'

### ISSUE THREAD

**Issue by dontbanmeplz** [jofpin/trape#307]
I get this error every time I run

**Comment by storeds** [comment]
me too

**Comment by zeeshan9113000** [comment]
I am also getting a same error

**Comment by storeds** [comment]
I hope this issue could be discuss , because I really don't know how  to do,thanks every sir

**Comment by lilwilly2** [comment]
same here

**Comment by C4l1b3r** [comment]
Same issue

**Comment by hello12324** [comment]
The more complete error is
Traceback (most recent call last):
   File "/root/trape/./trape.py", line 84, in <module>
     trackPeople.main()
   File "/root/trape/core/trape.py", line 234, in main
     import core.sockets
   File "/root/trape/core/sockets.py", line 18, in <module>
     import core.stats
   File "/root/trape/core/stats.py", line 24, in <module>
     trape = Trape(1)
   File "/root/trape/core/trape.py", line 77, in __init__
     parser = argparse.ArgumentParser("python trape.py -u <<Url>> -p <<Port>>", version=self.version)
TypeError: __init__() got an unexpected keyword argument'version'

**Comment by hello12324** [comment]
If there are always problems, you can modify it in core/trape.py, line 77
parser = argparse.ArgumentParser("python trape.py -u <> -p <>", version=self.version)
Change to
parser = argparse.ArgumentParser("python trape.py -u <> -p <>")
Can run normally~~

**Comment by metalpandit** [comment]
im also having the same issue :(

**Comment by metalpandit** [comment]
> If there are always problems, you can modify it in core/trape.py, line 77
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>", version=self.version)
> Change to
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>")
> Can run normally~~

thanx brother it worked for me.

**Comment by MillieBIllie** [comment]
if you are still having problems like "error exec..... './ngork.' " then go download latest version of ngork from their website (in my case linux ARM64 for a rasberry pi 4) and delete the existing ngork file and replace it with a newly downloaded file.......

**Comment by hipsterweeds** [comment]
> If there are always problems, you can modify it in core/trape.py, line 77
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>", version=self.version)
> Change to
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>")
> Can run normally~~

but i don't find on my code, in my code from line 77 is

![image](https://user-images.githubusercontent.com/53179024/118801478-42970f00-b8cb-11eb-8267-c28d3c17e182.png)


# Call the creation of the database when you open this file.
generateData.loadDatabase()

if __name__ == "__main__":
    try:
        # General expression this is expressed after the root
        trackPeople.main()
    except Exception as error:
        # Result of error
        utils.Go(utils.Color['whiteBold'] + "[" + utils.Color['redBold'] + "x" + utils.Color['whiteBold'] + "]" + utils.Color['redBold'] + " " + "ERROR: " + utils.Color['white'] + "%s" % error)

**Comment by xmi666** [comment]
there is another file that's named trape.py in the core folder. You have to make the changes there. (: also i do have a rewritten version of the python code on my GitHub. If u want to check it it, it has a few more bugfixes, that I also have proposed in my pull request.

**Comment by XDAS1979** [comment]
Help me,  Please 

Loading trape...
[x] ERROR: __init__() got an unexpected keyword argument 'version'

**Comment by captain-woof** [comment]
Created a new pull request that should fix the issue. Please accept. #313

**Comment by xmi666** [comment]
I already fixed it a few days ago.. and even restructured the python code. But it still wasn't pulled. As an alternative, if you want to work on this, you can create pull requests on my fork. @captain-woof

**Comment by hipsterweeds** [comment]
> there is another file that's named trape.py in the core folder. You have to make the changes there. (: also i do have a rewritten version of the python code on my GitHub. If u want to check it it, it has a few more bugfixes, that I also have proposed in my pull request.

<img width="1280" alt="Screen Shot 2021-05-24 at 18 22 46" src="https://user-images.githubusercontent.com/53179024/119340746-20333600-bcbd-11eb-934b-7505a4032965.png">

this works, thanks. sorry my bad didn't check other folders.

**Comment by Abhracodec** [comment]
> If there are always problems, you can modify it in core/trape.py, line 77
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>", version=self.version)
> Change to
> parser = argparse.ArgumentParser("python trape.py -u <> -p <>")
> Can run normally~~

how to do it? step by step maybe?..I'm sorry, but I'm a beginner
