### ISSUE TITLE
Error when browse the Lure and Control linl

### ISSUE THREAD

**Issue by stevenfonz** [jofpin/trape#38]
[2018-03-24 20:24:33,029] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python_codes\trape-master\trape-master\core\stats.py", line 71, in home_get_title
    html = opener.open(trape.url_to_clone).read()
  File "C:\Python27\lib\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: www.facebook.com

**Comment by v1cker** [comment]
You should input like python trape.py -u https://www.facebook.com -p PORT , add http:// or https://

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!

**Comment by M2z** [comment]
I am getting something very similar even though I am sure the --URL parameter is good
#########
[¡] Waiting for the users to fall...

[2018-11-29 08:48:27,765] ERROR in app: Exception on /get_title [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Downloads/T00Ls/trape/core/stats.py", line 94, in home_get_title
    html = opener.open(trape.url_to_clone).read()
  File "/root/Downloads/T00Ls/trape/core/dependence/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/root/Downloads/T00Ls/trape/core/dependence/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/root/Downloads/T00Ls/trape/core/dependence/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/root/Downloads/T00Ls/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/root/Downloads/T00Ls/trape/core/dependence/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by Prince-Hamza** [comment]
issue is still coming in trape for python3
