### ISSUE TITLE
double error on windows

### ISSUE THREAD

**Issue by Devcoding123** [jofpin/trape#60]
hi there, i'm trying to get trape working but I have 2 errors:
**the first one when doing pip install -r requirements.txt :** 
Collecting urllib2 (from -r requirements.txt (line 15))
  Could not find a version that satisfies the requirement urllib2 (from -r requirements.txt (line 15)) (from versions: )
No matching distribution found for urllib2 (from -r requirements.txt (line 15))

**the second one when I run the py file:**
 python trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "C:\Users\Desktop\trape\core\utils.py", line 23, in <module>
    import httplib
ImportError: No module named 'httplib'

any help please?
thx

**Comment by vdasu** [comment]
`urllib` is a part of standard library, remove it from `requirements.txt`. `httplib` is a part of Python 2, not 3. In Python3 it has been renamed to `http.client`.

**Comment by Devcoding123** [comment]
thx for the answer! should I rename httplib to http.client in my requirements.txt then or just use python 2?
I've removed everything mentionning urllib (several errors) and renaming httplib to http.client but i keep getting errors on errors...

**Comment by vdasu** [comment]
No, don't remove all occurrences of `urllib`,  remove it only from `requirements.txt` and run `pip install -r requirements.txt` again. As far simply renaming `httplib` to `http.client` is concerned, I'm not sure as to whether it would work. Try using a Python 2 to 3 converter such as [2to3](https://docs.python.org/2/library/2to3.html#).

**Comment by Devcoding123** [comment]
since we've talked the dev has updated its files, removed urllib from the requirements.txt, now there's a HEAD section that makes an error when I run pip install -r requirements.txt (no error when this section is deleted tho)

I've followed your advice and used 2to3 to convert the 'utils.py' file in C:\Users\Desktop\trape\core\utils.py 
but then I try to run python trape.py -h I still have the same error for httplib as in my first post...

it's driving me on the verge of insanity hahaha

**Comment by vdasu** [comment]
@pablojimpas you need to install `requests` using pip. 
@Devcoding123 have a look at #70 , it resolves the issue with the requirements file. Also it looks like this project has been designed to run on Python2. In most cases it shouldn't be too hard to convert legacy code to Python 3 using converters like 2to3. If it doesn't work I suggest you stick to Python2.

**Comment by pablojimpas** [comment]
> @pablojimpas you need to install `requests` using pip.

I've `requests` installed but since it is a Python 3 module when I run it with Python 2 it doesn't work. Does it work for you?

**Comment by vdasu** [comment]
You would need to install `requests` for Python2.

**Comment by Devcoding123** [comment]
I've done everything with python 2, but now a new error appears when I run **python trape.py -h** see for yourself lol: 

@@@@@@@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@
 @@@@@   @@@@@@@@@@@@@@@@
 @@@@@   @@@@@@@@@@@@@@@@
 @@@@@       @@     @@@@@
 @@@@@       @@     @@@@@
 @@@@@    @@@@@@@@@@@@@@@
 @@@@@    @@@@@     @@@@@
 @@@@@       @@     @@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@@@@@@
        -- v2.0 --

Traceback (most recent call last):
  File "trape.py", line 56, in <module>
    utils.Go(utils.Color['whiteBold'] + "WELCOME " + utils.Color['greenBold'] +
os.uname()[1].upper() + utils.Color['whiteBold'] + " TO TRAPE" + utils.Color['wh
ite'])
NameError: name 'os' is not defined

**Comment by Devcoding123** [comment]
any help?

**Comment by Mr-Virtual** [comment]
Same error coming for me
