### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Pescad0res** [jofpin/trape#64]
[2018-11-25 20:09:39,815] ERROR in app: Exception on /facebook.com [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/trape/core/user.py", line 69, in homeVictim
    html = assignScripts(victim_inject_code(opener.open(trape.url_to_clone).read(), 'payload', trape.url_to_clone, trape.gmaps))
  File "/root/trape/core/dependence/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/root/trape/core/dependence/urllib2.py", line 418, in _open
    '_open', req)
  File "/root/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/root/trape/core/dependence/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/root/trape/core/dependence/urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
[2018-11-25 20:11:52,408] ERROR in app: Exception on /facebook.com [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/trape/core/user.py", line 69, in homeVictim
    html = assignScripts(victim_inject_code(opener.open(trape.url_to_clone).read(), 'payload', trape.url_to_clone, trape.gmaps))
  File "/root/trape/core/dependence/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/root/trape/core/dependence/urllib2.py", line 418, in _open
    '_open', req)
  File "/root/trape/core/dependence/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/root/trape/core/dependence/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/root/trape/core/dependence/urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by hardworking-salmon** [comment]
same error
