### ISSUE TITLE
ImportError: No module named ordered_dict

### ISSUE THREAD

**Issue by cegar37** [jofpin/trape#77]
Hello,

I've a little trouble for using Trape. (requirements has been installed)

$ python trape.py -h                                                                    
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!                                                                                         
  RequestsDependencyWarning)                                                                                             
Traceback (most recent call last):                                                                                       
  File "trape.py", line 23, in <module>                                                                                  
    from core.utils import utils                  #                                                                      
  File "/home/tools/WEB/trape/core/utils.py", line 21, in <module>                                                       
    import requests, json                                                                                                
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>                                     
    from . import utils                                                                                                  
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>                                        
    from ._internal_utils import to_native_string                                                                        
  File "/usr/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>                              
    from .compat import is_py2, builtin_str, str                                                                         
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>                                       
    from urllib3.packages.ordered_dict import OrderedDict                                                                
ImportError: No module named ordered_dict          

Do you have an idea how can I solve the issue ?

Thanks for help

**Comment by cegar37** [comment]
Solved using 

pip uninstall urllib3

and then pip install urllib3==1.22

**Comment by Shivaraj18** [comment]
@cegar37 
Thank you so much, even it solved for me.

**Comment by mitter1989** [comment]
@cegar37 worked for me as well :+1: Thanks.
