### ISSUE TITLE
ModuleNotFoundError: No module named 'httplib'

### ISSUE THREAD

**Issue by rayy101** [jofpin/trape#81]
λ python trape.py -h
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "E:\cmder\trape\core\utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

**Comment by KashyapNasit** [comment]
You are running Python 2 code on Python 3. In Python 3, the module has been renamed to http.client.

**Comment by mpavar** [comment]
How to change the name

**Comment by DJCHICKEN4** [comment]
> How to change the name

`sudo apt install python`
navigate to the location of trape.
`python trape.py`

**Comment by KashyapNasit** [comment]
> How to change the name
You are running Python 2 code on Python 3. In Python 3, the module has been renamed to http.client

**Comment by empt1xo** [comment]
How to fix this error ?

**Comment by magzy445555555** [comment]
How to fix this error cannot find anywhere

**Comment by mrseeker53** [comment]
You are running Python 2 code on Python 3. In Python 3, the module ( 'httplib' ) has been renamed to 'http.client'

**Comment by tonovicio** [comment]
sudo ./trape.py
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/marlon/trape/core/utils.py", line 21, in <module>
    import requests,json
ImportError: No module named requests

**Comment by tonovicio** [comment]
sudo ./trape.py
Traceback (most recent call last):
  File "./trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/marlon/trape/core/utils.py", line 21, in <module>
    import requests, json
ImportError: No module named requests

**Comment by Gokulkannan007** [comment]
Hello Guys,
               I am encountering this problem
kali@kali:~/trape$  python trape.py -u www.google.om -p 19153
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/kali/trape/core/utils.py", line 23, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

can someone help me to get rid out of this problem
