### ISSUE TITLE
ErrorTraceback (most recent call last):   File "trape.py", line 23, in <module>

### ISSUE THREAD

**Issue by mpavar** [jofpin/trape#85]
Traceback (most recent call last):
  File "trape.py", line 23, in <module>

    from core.utils import utils                  #
  File "/data/data/com.termux/files/home/IPGeoLocation/trape/core/utils.py", line 21, in <module>
    import requests, json
ModuleNotFoundError: No module named 'requests'

**Comment by XxmathiasxX** [comment]
how?
