### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by blazedivibrations** [jofpin/trape#91]
F:\*****\Trape\trape>python2 trape.py
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "F:\*****\Trape\trape\core\utils.py", line 21, in <module>
   import requests, json
ImportError: No module named requests

**Comment by jaykaron** [comment]
You first need to install the python packages listed in `requirements.txt`.
You can install them with pip by running `pip install -r requirements.txt`.

**Comment by milindmadhukar** [comment]
> python2 trape.py -u google.com

Still shows the same error

**Comment by sevenmountains** [comment]
Same here

**Comment by Aditya7851-AdiStarCoders** [comment]
same problem

**Comment by jmague** [comment]
I guess it should be 
`pip2 install  -r requirements.txt`

**Comment by nakulkundra** [comment]
Still getting same error after installing all the requirements.
